trigger:
  branches:
    include:
    - main
  paths:
    include:
    - itabank.SDK/*

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'itabank.SDK/itabank.SDK.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Package'
  inputs:
    command: 'pack'
    packagesToPack: 'itabank.SDK/itabank.SDK.csproj'
    nobuild: false
    versioningScheme: 'byPrereleaseNumber'
    majorVersion: '1'
    minorVersion: '0'
    patchVersion: '0'
    
- task: DotNetCoreCLI@2
  displayName: 'Push'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '286ad473-3155-4c2d-a692-00bc7c74bdbb/d45a0b00-2205-43e8-a33e-1acfec305dc1'