trigger:
  branches:
    include:
    - main
  paths:
    include:
    - itabank.Core/*
    - itabank.SDK/*
    - itabank.SDK.Tests/*
    - itabank.Shared/*    
    - itabank.WebApi/*
    - itabank.WebApi.Tests/*
    exclude:
    - itabank.WebApi/webapi.arm.*

variables:
  appService: 'itabank-dev-webapi'
  appType: 'webApp'
  buildConfiguration: 'Release'
  pipelineArtifact: 'artifact'
  projectName: 'itabank.WebApi'
  subscription: 'itabank-service-connection'
  testProjectName: 'itabank.Core'

stages:
- stage: Build
  displayName: 'Build'
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '$(projectName)/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: 'Test - $(testProjectName)'
      inputs:
        command: 'test'
        projects: '$(testProjectName).Tests/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Test - $(projectName)'
      inputs:
        command: 'test'
        projects: '$(projectName).Tests/*.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Publish Project'
      inputs:
        command: 'publish'
        projects: '$(projectName)/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        publishWebProjects: false
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: '$(pipelineArtifact)'

- stage: Deploy
  displayName: 'Deploy'
  dependsOn: Build
  condition: succeeded()
  pool:
    vmImage: ubuntu-latest
  jobs:
  - deployment: DeployToAzure
    displayName: 'Deploy'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download'
            inputs:
              artifact: '$(pipelineArtifact)'
              path: '$(Pipeline.Workspace)/$(pipelineArtifact)'
          - task: AzureWebApp@1
            displayName: 'Deploy'
            inputs:
              azureSubscription: '$(subscription)'
              appName: '$(appService)'
              appType: '$(appType)'
              package: '$(Pipeline.Workspace)/$(pipelineArtifact)/*.zip'
              deploymentMethod: 'auto'