trigger:
  branches:
    include:
    - main
  paths:
    include:
    - itabank.Core/*
    - itabank.WebApi/*
    - itabank.WebApi.Tests/*

variables:
  azureSubscription: 'itabank-service-connection'
  appServiceName: 'itabank-dev-webapi'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build & Test'
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: BuildAndTest
    displayName: 'Build & Test'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: 'itabank.WebApi/itabank.WebApi.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: 'Test - itabank.Core'
      inputs:
        command: 'test'
        projects: 'itabank.Core.Tests/itabank.Core.Tests.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Test - itabank.WebApi'
      inputs:
        command: 'test'
        projects: 'itabank.WebApi.Tests/itabank.WebApi.Tests.csproj'
    - task: DotNetCoreCLI@2
      displayName: 'Publish'
      inputs:
        command: 'publish'
        projects: 'itabank.WebApi/itabank.WebApi.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        publishWebProjects: false
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'webapi-drop'

- stage: Deploy
  displayName: 'Deploy'
  dependsOn: Build
  condition: succeeded()
  pool:
    vmImage: ubuntu-latest
  jobs:
  - deployment: DeployToAzure
    displayName: 'Deploy'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'webapi-drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureWebApp@1
            displayName: 'Deploy'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: '$(appServiceName)'
              package: '$(System.ArtifactsDirectory)/webapi-drop/**/*.zip'
              deploymentMethod: 'auto'