trigger:
  branches:
    include:
    - main
  paths:
    include:
    - itabank.Function/function.arm.*

variables:
  armTemplate: 'function.arm.json'
  location: 'UK South'
  pipelineArtifact: 'artifact'
  projectName: 'itabank.Function'
  resourceGroup: 'itabank-dev-function'
  serviceConnection: 'itabank-service-connection'
  subscription: '47e3a40f-35ad-4332-b501-a4036f561613'

stages:
- stage: Validate
  displayName: 'Validate'
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: Validate
    displayName: 'Validate'
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Validate'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(serviceConnection)'
        subscriptionId: '$(subscription)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroup)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(Build.SourcesDirectory)/$(projectName)/$(armTemplate)'
        deploymentMode: 'Validation'
    - task: PublishPipelineArtifact@1
      displayName: 'Publish'
      inputs:
        targetPath: '$(Build.SourcesDirectory)/$(projectName)/$(armTemplate)'
        artifact: '$(pipelineArtifact)'

- stage: Deploy
  displayName: 'Deploy'
  dependsOn: Validate
  condition: succeeded()
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: Deploy
    displayName: 'Deploy'
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: 'Download'
      inputs:
        artifact: '$(pipelineArtifact)'
        path: '$(Pipeline.Workspace)/$(pipelineArtifact)'
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'Deploy'
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: '$(serviceConnection)'
        subscriptionId: '$(subscription)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroup)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/$(pipelineArtifact)/$(armTemplate)'
        deploymentMode: 'Incremental'