trigger:
  branches:
    include:
    - main
  paths:
    include:
    - itabank.Function/*
    - itabank.Function.Tests/*
    - itabank.SDK/*
    - itabank.SDK.Tests/*
    - itabank.Shared/*
    exclude:
    - itabank.Function/function.arm.*

variables:
  appService: 'itabank-dev-update-account'
  appType: 'functionAppLinux'
  buildConfiguration: 'Release'
  pipelineArtifact: 'artifact'
  projectName: 'itabank.Function'
  runtime: 'DOTNET-ISOLATED|9.0'
  subscription: 'itabank-service-connection'
  testProjectName: 'itabank.SDK'

stages:
- stage: Build
  displayName: 'Build'
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: '$(projectName)/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: 'Test - $(testProjectName)'
      inputs:
        command: 'test'
        projects: '$(testProjectName).Tests/*.csproj'        
    - task: DotNetCoreCLI@2
      displayName: 'Publish Project'
      inputs:
        command: 'publish'
        projects: '$(projectName)/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        publishWebProjects: false
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: '$(pipelineArtifact)'

- stage: Deploy
  displayName: 'Deploy'
  dependsOn: Build
  condition: succeeded()
  pool:
    vmImage: ubuntu-latest
  jobs:
  - deployment: DeployToAzure
    displayName: 'Deploy'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@2
            displayName: 'Deploy'
            inputs:
              appName: '$(appService)'
              appType: '$(appType)'
              connectedServiceNameARM: '$(subscription)'
              package: '$(Pipeline.Workspace)/$(pipelineArtifact)/*.zip'
              runtimeStack: '$(runtime)'