trigger:
  branches:
    include:
    - main
  paths:
    include:
    - itabank.Function/*
    - itabank.Function.Tests/*
    - itabank.SDK/*
    - itabank.SDK.Tests/*
    - itabank.Shared/*
    exclude:
    - itabank.Function/function.arm.*

variables:
  azureSubscription: 'itabank-service-connection'
  appServiceName: 'itabank-dev-webapi'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build'
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: Build
    displayName: 'Build'
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build'
      inputs:
        command: 'build'
        projects: 'itabank.Function/itabank.Function.csproj'
        arguments: '--configuration $(buildConfiguration)'