---
version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04
    hostname: mssql
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_AGENT_ENABLED: 'True'
      SA_PASSWORD: 'b11a8fe75d7866ee3fB1f871589493123'
